### ISSUE TITLE
BUG: Serializer ListField with child serializer having validators

### ISSUE THREAD

**Issue by omerfarukabaci** [Hipo/hipo-drf-exceptions#22]
To reproduce the issue, the following setup should be enough:

```python
class Foo(serializers.Serializer):
    bars = serializers.ListField(child=serializers.IntegerField(min_value=1, allow_null=False), allow_empty=False, required=False)
```

Add this serializer to a view then with POST method send this payload:

```python
{
    "bars": [0, 1, 2, 3, 10]
}
```

It results in the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 242, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'bars': {0: [ErrorDetail(string='Ensure this value is greater than or equal to 1.', code='min_value')]}}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 462, in handle_exception
    response = exception_handler(exc, context)
  File "/usr/local/lib/python3.8/site-packages/hipo_drf_exceptions/handlers.py", line 87, in handler
    'fallback_message': get_fallback_message(exc)
  File "/usr/local/lib/python3.8/site-packages/hipo_drf_exceptions/handlers.py", line 40, in get_fallback_message
    return get_fallback_message(exception.detail)
  File "/usr/local/lib/python3.8/site-packages/hipo_drf_exceptions/handlers.py", line 37, in get_fallback_message
    return get_fallback_message(message)
  File "/usr/local/lib/python3.8/site-packages/hipo_drf_exceptions/handlers.py", line 32, in get_fallback_message
    message = get_human_readable_concatenation_of(first_key, message[0])
  File "/usr/local/lib/python3.8/site-packages/hipo_drf_exceptions/handlers.py", line 13, in get_human_readable_concatenation_of
    human_readable_key = " ".join(key.split("_")).title()
AttributeError: 'int' object has no attribute 'split'
```

If I remove the `min_value` validator from the child serializer it works.

**Comment by omerfarukabaci** [comment]
This issue should be fixed with https://github.com/Hipo/hipo-drf-exceptions/pull/25. So I am closing this.
