### ISSUE TITLE
Bulk Errors

### ISSUE THREAD

**Issue by efe** [Hipo/hipo-drf-exceptions#8]
The package fails dictionary errors without any key in Bulk endpoints.

Example Exception:
```
[{}, {}, {'phone_number': [ErrorDetail(string='The phone number entered is not valid.', code='invalid_phone_number')]}, {}, {}]
```

Example Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 452, in handle_exception
    response = exception_handler(exc, context)
  File "/usr/local/lib/python3.7/site-packages/hipo_drf_exceptions/handlers.py", line 63, in handler
    'fallback_message': get_fallback_message(exc)
  File "/usr/local/lib/python3.7/site-packages/hipo_drf_exceptions/handlers.py", line 21, in get_fallback_message
    return get_fallback_message(exception.detail)
  File "/usr/local/lib/python3.7/site-packages/hipo_drf_exceptions/handlers.py", line 15, in get_fallback_message
    return get_fallback_message(exception[0])
  File "/usr/local/lib/python3.7/site-packages/hipo_drf_exceptions/handlers.py", line 17, in get_fallback_message
    first_key = next(iter(exception))
StopIteration
```

**Comment by dogrultan** [comment]
Possible duplicate of https://github.com/Hipo/hipo-drf-exceptions/issues/6?

**Comment by efe** [comment]
Done.
